name: Build & Test

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: zhxiaogg/cargo-static-build@master
        with:
          cmd: cargo test --target x86_64-unknown-linux-musl
